---
- name: Upload to S3 and Invalidate CloudFront
  hosts: localhost
  tasks:
    - name: Checkout code
      git:
        repo: 'https://github.com/BenjaminBurton/ansible-testBook.git'
        dest: /Users/Apple/Documents/LevLUp/AWS/Projects/CDA/CI:CD/Ansible

    - name: Configure AWS credentials
      set_fact:
        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        aws_region: "us-east-1"

    - name: Upload index.html to S3
      shell: |
        aws s3 cp /Users/Apple/Documents/LevLUp/AWS/Projects/CDA/CI:CD/Ansible/index.html s3://ansible-testrun/index.html --acl public-read
        aws s3 cp /Users/Apple/Documents/LevLUp/AWS/Projects/CDA/CI:CD/Ansible/resume.css s3://ansible-testrun/resume.css --acl public-read
      environment:
        AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
        AWS_DEFAULT_REGION: "{{ aws_region }}"

    - name: Invalidate CloudFront
      shell: |
        aws cloudfront create-invalidation \
          --distribution-id E2JL33EXZRPDR0 \
          --paths "/index.html"
      environment:
        AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
        AWS_DEFAULT_REGION: "{{ aws_region }}"