name: Upload to S3 and Invalidate CloudFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository to access index.html
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change to your region

      # Step 3: Upload index.html to S3 bucket
      - name: Upload index.html to S3
        run: |
          aws s3 cp index.html s3://mylevelupcloudresume/index.html --acl public-read
          aws s3 cp resume.css s3://mylevelupcloudresume/resume.css --acl public-read

      # Step 4: Invalidate CloudFront cache to serve updated content
      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E3AGBKPOHEWHPQ   \
            --paths "/index.html"